# Generated by Django 4.2.1 on 2023-07-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_city',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_fname',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_lname',
            new_name='lname',
        ),
    ]
