# Generated by Django 4.2.1 on 2023-07-09 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0004_remove_post_num_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_user', to='scholar.post')),
                ('user', models.ManyToManyField(related_name='user_liked_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
