# Generated by Django 4.2.1 on 2023-07-09 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0005_remove_post_likes_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liked',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='liked',
            name='user',
        ),
        migrations.AddField(
            model_name='liked',
            name='posts',
            field=models.ManyToManyField(related_name='liked_times', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='liked',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_liked_posts', to='scholar.post'),
        ),
    ]
