# Generated by Django 4.2.1 on 2023-07-09 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_remove_liked_posts_remove_liked_user_liked_posts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liked',
            name='posts',
            field=models.ManyToManyField(related_name='liked_times', to='scholar.post'),
        ),
        migrations.AlterField(
            model_name='liked',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_liked_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
