# Generated by Django 4.2.1 on 2023-07-09 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0011_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='favorite_of_users',
            field=models.ManyToManyField(related_name='favorite_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
